sources:
  - name: jaffle_shop
    description: This is a replica of a Postgre datbase used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: one record per customer and this a raw data
        columns:
          - name: id
            description: Primary key
            tests:
              - unique
              - not_null
      - name: orders
        description: one record per order. Includes cancelled and deleted order.
        columns:
          - name: id
            description: Primary Key
            tests:
              - unique
              - not_null
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _ETL_LOADED_AT

  - name: stripe  
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: This has all the payment data.
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}


        
  